{% set name = "tyro" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tyro-{{ version }}.tar.gz
  sha256: 1f6c8fe19040e2f8bde32013c5255693a2f311d3599bb051474bc92561de25e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - docstring_parser >=0.14.1
    - typing-extensions >=4.9.0
    - pyyaml >=6.0
    - colorama >=0.4.0
    - frozendict >=2.3.4
    - rich >=11.1.0
    - shtab >=1.5.6
    - eval_type_backport >=0.1.3

test:
  imports:
    - tyro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/brentyi/tyro
  summary: Strongly typed, zero-effort CLI interfaces
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
